---
title: "Covid data from {NHSRdatasets}"
format: html
params:
  country: "New_Zealand"
  month_start: "2019-12-01"
  month_end: "2020-12-01"
---

```{r}
#| label: packages
#| eval: true
#| include: false
library(tidyverse)
library(NHSRdatasets)

# Note to get the covid19 data the installation needs to be from GitHub not CRAN
# install.packages("remotes")
# remotes::install_github("nhs-r-community/NHSRdatasets")
```

```{r}
total_records <- NHSRdatasets::covid19 |>
  filter(countries_and_territories == params$country) |>
  summarise(total = n())

```

# Country analysis

## Overview

There are `r total_records` records for `r params$country %>% stringr::str_replace("_", " ")` for the period `r format(lubridate::as_datetime(params$month_start), '%d %B %Y')` to `r format(lubridate::as_datetime(params$month_end), '%d %B %Y')`.

## Covid cases

```{r}
data <- NHSRdatasets::covid19 |> 
  mutate(month = lubridate::floor_date(date_reported, unit = "month")) |> 
  filter(countries_and_territories == params$country,
         month >= params$month_start & month <= params$month_end)

ggplot(data, aes(x = date_reported, 
                 y = cases)) + 
  geom_point() + 
  geom_line() + 
  labs(
    x = "Date reported", 
    y = "Covid reported cases"
  ) +
  expand_limits(y = 0) 
```